name: dart_monty_desktop
description: Desktop plugin for dart_monty â€” Dart/Flutter bindings for Monty, a Rust-built embeddable sandbox running a restricted subset of Python.
version: 0.3.3
homepage: https://github.com/runyaga/dart_monty
repository: https://github.com/runyaga/dart_monty
issue_tracker: https://github.com/runyaga/dart_monty/issues
topics:
  - python
  - sandbox
  - ffi
  - flutter

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.10.0'

dependencies:
  dart_monty_ffi: ^0.3.3
  dart_monty_platform_interface: ^0.3.3
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  test: ^1.25.0
  very_good_analysis: ^10.0.0

flutter:
  plugin:
    implements: dart_monty
    platforms:
      macos:
        dartPluginClass: DartMontyDesktop
        ffiPlugin: true
      linux:
        dartPluginClass: DartMontyDesktop
        ffiPlugin: true
