name: dart_monty
description: Flutter plugin exposing the Monty sandboxed Python interpreter to Dart/Flutter via FFI (native) and JS interop (web).
publish_to: https://pub.dev
version: 0.3.2
homepage: https://github.com/runyaga/dart_monty
repository: https://github.com/runyaga/dart_monty
issue_tracker: https://github.com/runyaga/dart_monty/issues
topics:
  - python
  - sandbox
  - interpreter
  - flutter

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: '>=3.19.0'

dependencies:
  dart_monty_desktop:
    path: packages/dart_monty_desktop
  dart_monty_platform_interface:
    path: packages/dart_monty_platform_interface
  dart_monty_web:
    path: packages/dart_monty_web
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^10.0.0

flutter:
  plugin:
    platforms:
      linux:
        default_package: dart_monty_desktop
      macos:
        default_package: dart_monty_desktop
      web:
        default_package: dart_monty_web
