name: dart_monty_wasm
description: Web WASM implementation of dart_monty using dart:js_interop and @pydantic/monty.
publish_to: 'none'
version: 0.3.1
homepage: https://github.com/runyaga/dart_monty
repository: https://github.com/runyaga/dart_monty
issue_tracker: https://github.com/runyaga/dart_monty/issues
topics:
  - python
  - sandbox
  - wasm
  - interpreter

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  dart_monty_platform_interface:
    path: ../dart_monty_platform_interface

dev_dependencies:
  test: ^1.25.0
  very_good_analysis: ^10.0.0
