name: dart_monty_native
description: Native plugin for dart_monty, pure Dart bindings for Monty â€” a restricted sandboxed Python interpreter built in Rust.
version: 0.6.0
homepage: https://github.com/runyaga/dart_monty
repository: https://github.com/runyaga/dart_monty
issue_tracker: https://github.com/runyaga/dart_monty/issues
topics:
  - python
  - sandbox
  - ffi
  - flutter

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.10.0'

dependencies:
  dart_monty_ffi: ^0.4.0
  dart_monty_platform_interface: ^0.4.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.25.0
  very_good_analysis: ^10.0.0

dependency_overrides:
  dart_monty_ffi:
    path: ../dart_monty_ffi
  dart_monty_platform_interface:
    path: ../dart_monty_platform_interface

flutter:
  plugin:
    implements: dart_monty
    platforms:
      macos:
        dartPluginClass: DartMontyNative
        ffiPlugin: true
      linux:
        dartPluginClass: DartMontyNative
        ffiPlugin: true
