name: dart_monty_platform_interface
description: Platform interface for dart_monty. Defines the shared API contract implemented by native and web backends.
publish_to: 'none'
version: 0.3.2
homepage: https://github.com/runyaga/dart_monty
repository: https://github.com/runyaga/dart_monty
issue_tracker: https://github.com/runyaga/dart_monty/issues
topics:
  - python
  - sandbox
  - interpreter

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  collection: ^1.18.0
  meta: ^1.11.0
  plugin_platform_interface: ^2.1.8

dev_dependencies:
  mocktail: ^1.0.4
  test: ^1.25.0
  very_good_analysis: ^10.0.0
