name: dart_monty_ffi
description: Native FFI implementation of dart_monty for desktop and mobile platforms (macOS, Linux, Windows, iOS, Android).
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: '>=3.5.0 <4.0.0'
  flutter: '>=3.24.0'

dependencies:
  dart_monty_platform_interface:
    path: ../dart_monty_platform_interface
  ffi: ^2.1.3
  flutter:
    sdk: flutter

dev_dependencies:
  ffigen: ^16.0.0
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^10.0.0
