name: dart_monty_ffi
description: Native FFI implementation of dart_monty for desktop and mobile platforms (macOS, Linux, Windows, iOS, Android).
publish_to: 'none'
version: 0.3.1
homepage: https://github.com/runyaga/dart_monty
repository: https://github.com/runyaga/dart_monty
issue_tracker: https://github.com/runyaga/dart_monty/issues
topics:
  - python
  - sandbox
  - ffi
  - interpreter

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  dart_monty_platform_interface:
    path: ../dart_monty_platform_interface
  ffi: ^2.1.3

dev_dependencies:
  ffigen: ^20.1.1
  test: ^1.25.0
  very_good_analysis: ^10.0.0
