name: Publish platform_interface

on:
  push:
    tags:
      - 'platform_interface-v[0-9]*.[0-9]*.[0-9]*'

jobs:
  publish:
    uses: ./.github/workflows/_publish-dart-package.yaml
    permissions:
      id-token: write
    with:
      package-name: dart_monty_platform_interface
      tag-prefix: platform_interface-v
      package-path: packages/dart_monty_platform_interface
