name: Publish ffi

on:
  push:
    tags:
      - 'ffi-v[0-9]*.[0-9]*.[0-9]*'

jobs:
  publish:
    uses: ./.github/workflows/_publish-dart-package.yaml
    permissions:
      id-token: write
    with:
      package-name: dart_monty_ffi
      tag-prefix: ffi-v
      package-path: packages/dart_monty_ffi
      needs-ffigen: true
