name: Publish desktop

on:
  push:
    tags:
      - 'desktop-v[0-9]*.[0-9]*.[0-9]*'

jobs:
  publish:
    uses: ./.github/workflows/_publish-dart-package.yaml
    permissions:
      id-token: write
    with:
      package-name: dart_monty_desktop
      tag-prefix: desktop-v
      package-path: packages/dart_monty_desktop
      uses-flutter: true
