name: Publish web

on:
  push:
    tags:
      - 'web-v[0-9]*.[0-9]*.[0-9]*'

jobs:
  publish:
    uses: ./.github/workflows/_publish-dart-package.yaml
    permissions:
      id-token: write
    with:
      package-name: dart_monty_web
      tag-prefix: web-v
      package-path: packages/dart_monty_web
      uses-flutter: true
      has-tests: false
