name: Publish dart_monty

on:
  push:
    tags:
      - 'dart_monty-v[0-9]*.[0-9]*.[0-9]*'

jobs:
  publish:
    uses: ./.github/workflows/_publish-dart-package.yaml
    permissions:
      id-token: write
    with:
      package-name: dart_monty
      tag-prefix: dart_monty-v
      uses-flutter: true
      has-tests: false
      analyze-scope: lib
